{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import tkinter as tk\n",
    "from tkinter import filedialog\n",
    "from PIL import Image, ImageTk\n",
    "import cv2\n",
    "import numpy as np\n",
    "from tensorflow.keras.models import load_model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"d:\\SKAY\\Programs\\Anaconda\\envs\\suii\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\asame\\AppData\\Local\\Temp\\ipykernel_12776\\2742100165.py\", line 18, in predict_image\n",
      "    prediction = model.predict(img_processed)\n",
      "  File \"d:\\SKAY\\Programs\\Anaconda\\envs\\suii\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py\", line 1727, in predict\n",
      "    tmp_batch_outputs = self.predict_function(iterator)\n",
      "  File \"d:\\SKAY\\Programs\\Anaconda\\envs\\suii\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 889, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"d:\\SKAY\\Programs\\Anaconda\\envs\\suii\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 933, in _call\n",
      "    self._initialize(args, kwds, add_initializers_to=initializers)\n",
      "  File \"d:\\SKAY\\Programs\\Anaconda\\envs\\suii\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 764, in _initialize\n",
      "    *args, **kwds))\n",
      "  File \"d:\\SKAY\\Programs\\Anaconda\\envs\\suii\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3050, in _get_concrete_function_internal_garbage_collected\n",
      "    graph_function, _ = self._maybe_define_function(args, kwargs)\n",
      "  File \"d:\\SKAY\\Programs\\Anaconda\\envs\\suii\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3444, in _maybe_define_function\n",
      "    graph_function = self._create_graph_function(args, kwargs)\n",
      "  File \"d:\\SKAY\\Programs\\Anaconda\\envs\\suii\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3289, in _create_graph_function\n",
      "    capture_by_value=self._capture_by_value),\n",
      "  File \"d:\\SKAY\\Programs\\Anaconda\\envs\\suii\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 999, in func_graph_from_py_func\n",
      "    func_outputs = python_func(*func_args, **func_kwargs)\n",
      "  File \"d:\\SKAY\\Programs\\Anaconda\\envs\\suii\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 672, in wrapped_fn\n",
      "    out = weak_wrapped_fn().__wrapped__(*args, **kwds)\n",
      "  File \"d:\\SKAY\\Programs\\Anaconda\\envs\\suii\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 986, in wrapper\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    d:\\SKAY\\Programs\\Anaconda\\envs\\suii\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py:1569 predict_function  *\n",
      "        return step_function(self, iterator)\n",
      "    d:\\SKAY\\Programs\\Anaconda\\envs\\suii\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py:1559 step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    d:\\SKAY\\Programs\\Anaconda\\envs\\suii\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:1285 run\n",
      "        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)\n",
      "    d:\\SKAY\\Programs\\Anaconda\\envs\\suii\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:2833 call_for_each_replica\n",
      "        return self._call_for_each_replica(fn, args, kwargs)\n",
      "    d:\\SKAY\\Programs\\Anaconda\\envs\\suii\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:3608 _call_for_each_replica\n",
      "        return fn(*args, **kwargs)\n",
      "    d:\\SKAY\\Programs\\Anaconda\\envs\\suii\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py:1552 run_step  **\n",
      "        outputs = model.predict_step(data)\n",
      "    d:\\SKAY\\Programs\\Anaconda\\envs\\suii\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py:1525 predict_step\n",
      "        return self(x, training=False)\n",
      "    d:\\SKAY\\Programs\\Anaconda\\envs\\suii\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\base_layer.py:1013 __call__\n",
      "        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)\n",
      "    d:\\SKAY\\Programs\\Anaconda\\envs\\suii\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\input_spec.py:270 assert_input_compatibility\n",
      "        ', found shape=' + display_shape(x.shape))\n",
      "\n",
      "    ValueError: Input 0 is incompatible with layer sequential: expected shape=(None, 224, 224, 3), found shape=(None, 150, 150, 3)\n",
      "\n"
     ]
    }
   ],
   "source": [
    "# Load your trained model\n",
    "model = load_model('D:\\\\SKAY\\\\Projects\\\\KEEP\\\\VScode\\\\Ocular Recognition Disease\\\\my_occular_trained_model.h5')  \n",
    "\n",
    "# Function to preprocess images for prediction\n",
    "def preprocess_image(img):\n",
    "    img = cv2.resize(img, (150, 150))\n",
    "    img = img / 255.0  # Normalize pixel values to [0, 1]\n",
    "    return img\n",
    "\n",
    "# Function to make predictions and update the GUI\n",
    "def predict_image():\n",
    "    file_path = filedialog.askopenfilename(title=\"Select an Image\", filetypes=[(\"Image files\", \"*.jpg;*.jpeg;*.png\")])\n",
    "    if file_path:\n",
    "        img = cv2.imread(file_path)\n",
    "        img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)\n",
    "        img_processed = preprocess_image(img_rgb)\n",
    "        img_processed = np.expand_dims(img_processed, axis=0)\n",
    "        prediction = model.predict(img_processed)\n",
    "       # predicted_class = \"Pneumonia\" if prediction > 0.5 else \"Normal\"\n",
    "\n",
    "    \n",
    "\n",
    "        # Get the class with the highest probability\n",
    "        predicted_class = np.argmax(predictions)\n",
    "\n",
    "\n",
    "        # Update the GUI with the result\n",
    "        result_label.config(text=f\"Prediction: {predicted_class}\")\n",
    "\n",
    "        # Display the selected image in the GUI\n",
    "        img = Image.fromarray(img_rgb)\n",
    "        img.thumbnail((300, 300))\n",
    "        img = ImageTk.PhotoImage(img)\n",
    "        image_label.config(image=img)\n",
    "        image_label.image = img\n",
    "\n",
    "# Create the main window\n",
    "root = tk.Tk()\n",
    "root.title(\"Occular Disease Classification App\")\n",
    "\n",
    "# Create and configure widgets\n",
    "select_button = tk.Button(root, text=\"Select Image\", command=predict_image)\n",
    "result_label = tk.Label(root, text=\"Prediction: \")\n",
    "image_label = tk.Label(root)\n",
    "\n",
    "# Pack widgets\n",
    "select_button.pack(pady=10)\n",
    "result_label.pack(pady=10)\n",
    "image_label.pack()\n",
    "\n",
    "# Start the main event loop\n",
    "root.mainloop()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "suii",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
